### ISSUE TITLE
Error running this action

### ISSUE THREAD

**Issue by fakoua** [denolib/deno-action#10]
Hi, 
I tried this action, i got an error on "GitHub Action for Deno" -> Run denolib/deno-action@0.19.0

`/usr/local/bin/docker-entrypoint.sh: 9: exec: /root/.deno/bin/deno: not found
`
Thanks

**Comment by axetroy** [comment]
@fakoua 

Deno-action is currently deprecated

Please use https://github.com/denolib/setup-deno instead

**Comment by fakoua** [comment]
Many thanks

**Comment by zhmushan** [comment]
@axetroy should we mark this repo as archived?

**Comment by axetroy** [comment]
@zhmushan 

yeah. it should be done

But currently I don’t have administrator permission for this repository
